### PR TITLE
Observe TestGenerateExamples changed output

### LINKED ISSUE #273: TestGenerateExamples produces a dirty work tree
### What happened?

Running tests with `PULUMI_ACCEPT=false` still produces a dirty work tree.

### Steps to reproduce

```
PULUMI_ACCEPT=false go test --run=TestGenerateExamples/azure-app-service  --count=1 ./...
```

### Expected Behavior

Clean work tree or error.

### Actual Behavior

Dirty work tree:
```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   pkg/tests/transpiled_examples/azure-app-service/nodejs/index.ts
	modified:   pkg/tests/transpiled_examples/azure-app-service/python/__main__.py

no changes added to commit (use "git add" and/or "git commit -a")
```

### Versions used

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Tests will now fail when codegened output changes without `PULUMI_ACCEPT=true`. 

Fixes #273

### CODE REVIEW

File: pkg/tests/transpiled_examples/azure-app-service/nodejs/index.ts [hunk 1]
```diff
@@ -75,7 +75,7 @@ const app = new azure_native.web.WebApp("app", {
         appSettings: [
             {
                 name: "WEBSITE_RUN_FROM_PACKAGE",
-                value: pulumi.interpolate`https://${sa.name}.blob.core.windows.net/${container.name}/${blob.name}?${blobAccessToken}`,
+                value: pulumi.all([sa.name, container.name, blob.name, blobAccessToken]).apply(([saName, containerName, blobName, blobAccessToken]) => `https://${saName}.blob.core.windows.net/${containerName}/${blobName}?${blobAccessToken}`),
```
Comment (AaronFriel) [inline pkg/tests/transpiled_examples/azure-app-service/nodejs/index.ts:78]: Interesting regression here.

Comment (iwahbe) [reply pkg/tests/transpiled_examples/azure-app-service/nodejs/index.ts:78]: That regression already exists in main, we just didn't notice it since the tests don't fail when output changes.

**Review by AaronFriel — APPROVED** [review]
