### PR TITLE
Fix panic when resource shape is invalid

### LINKED ISSUE #668: Panic on invalid resource when valid error is expected
### What happened?

In latest Pulumi yaml dependencies, the new client version panics when I instead expect the following error `resources.badResource must be an object;`

> [!NOTE]  
> This may be more appropriate in https://github.com/pulumi/pulumi feel free to move the issue there for tracking

### Example

```yaml
name: my-test-yaml
description: A stack that will throw an error.
runtime: yaml
template:
  description: A minimal Pulumi YAML program

config: {}
variables:     {}
resources:     {badResource}
outputs:       {}
```

Panic
```
Diagnostics:
  pulumi:pulumi:Stack (my-test-yaml-panic-repro):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x108 pc=0x10180f4dc]
    goroutine 37 [running]:
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.LoadDir({0x101a45f20, 0x1})
    	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:145 +0x25c
    github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.Load(...)
    	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/pulumiyaml/run.go:50
    github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).loadTemplate(0x14000628540, {0x0?, 0x1400028f638?, 0x100d9bad0?})
    	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:77 +0x6c
    github.com/pulumi/pulumi-yaml/pkg/server.(*yamlLanguageHost).GetRequiredPlugins(0x1025bef50?, {0x101cb3780?, 0x40?}, 0x101b32640?)
    	/home/runner/work/pulumi-yaml/pulumi-yaml/pkg/server/server.go:97 +0x30
    github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GetRequiredPlugins_Handler.func1({0x101d3e6b8?, 0x140006afe00?}, {0x101c76d60?, 0x14000300900?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/proto/go/language_grpc.pb.go:311 +0xd0
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x101d3e6b8, 0x140006af020}, {0x101c76d60, 0x14000300900}, 0x140006a6440, 0x140003b2ba0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
    github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GetRequiredPlugins_Handler({0x101cb3780, 0x14000628540}, {0x101d3e6b8, 0x140006af020}, 0x1400021c380, 0x140003d2320)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/proto/go/language_grpc.pb.go:313 +0x148
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140002c2000, {0x101d3e6b8, 0x140006aef90}, {0x101d4b500, 0x140002d8000}, 0x14000000900, 0x140003af140, 0x1025d7f40, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xb58
    google.golang.org/grpc.(*Server).handleStream(0x140002c2000, {0x101d4b500, 0x140002d8000}, 0x14000000900)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xb20
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 65
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x13c

error: failed to discover plugin requirements: error reading from server: EOF
```

Expected Error
```
resources.badResource must be an object;
```

### Output of `pulumi about`

This actually causes Pulumi about to panic as well. I am on pulumi cli `v3.137.0`

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #668 

I believe the issue is that we assign packages to the parsed template without checking diagnostics:
```
packages, err := packages.SearchPackageDecls(directory)
template.Packages = packages
```

### CODE REVIEW

File: pkg/pulumiyaml/run.go [hunk 1]
```diff
@@ -133,6 +133,10 @@ func LoadDir(directory string) (*ast.TemplateDecl, syntax.Diagnostics, error) {
 		return nil, diags, err
 	}
 
+	if diags.HasErrors() {
```
Comment (Frassle) [inline pkg/pulumiyaml/run.go:136]: Shouldn't we still do SeachPackageDecls so we can add that to the diagnostics as well if it errors but then check if template is nil just before assigning Packages to it?

Comment (Zaid-Ajaj) [reply pkg/pulumiyaml/run.go:136]: I mean if the template has errors while parsing, we would early exit like most Go functions, unless it is a pattern to combine errors from functions downstream. I don't have a strong opinion about this, could fix it either way

Comment (Frassle) [reply pkg/pulumiyaml/run.go:136]: Yeh fine, easy to change if a compelling reason comes up later

**Review by Frassle — APPROVED** [review]
